### ISSUE TITLE
crashes on Sequoia upon starting a download (almos any app DL)

### ISSUE THREAD

**Issue by Potato-007** [X1a0He/Adobe-Downloader#1]
I tried AE, ME, BR...

(Intel)

**Comment by X1a0He** [comment]
> 老板，什么时候支持12.0

最新版已支持12.0
https://github.com/X1a0He/Adobe-Downloader/releases/tag/1.1.0

**Comment by X1a0He** [comment]
> I tried AE, ME, BR...
> 
> (Intel)

I tried downloading on macOS 12 - 15 and there were no crashes. If possible, please provide the corresponding crash report

Console -> Crash Reports

**Comment by Potato-007** [comment]
macOS reinstall helped, now OK
