### ISSUE TITLE
Crashes when I click on the Settings cog

### ISSUE THREAD

**Issue by jollygiraffe** [X1a0He/Adobe-Downloader#10]
[Adobe Downloader 1.2.0 crash report.pdf](https://github.com/user-attachments/files/17707379/Adobe.Downloader.1.2.0.crash.report.pdf)

Crash report attached

**Comment by X1a0He** [comment]
Please try [1.3.0](https://github.com/X1a0He/Adobe-Downloader/releases/tag/1.3.0)
