### ISSUE TITLE
Exit Code: -1   

### ISSUE THREAD

**Issue by KutfeRen** [X1a0He/Adobe-Downloader#11]
I enter the correct password, but there is always an error. I can't install the programs.

**Comment by X1a0He** [comment]
Please try [1.3.0](https://github.com/X1a0He/Adobe-Downloader/releases/tag/1.3.0)

**Comment by ledunguit** [comment]
Really appreciate your contribution @X1a0He 

I've tried 1.3.0, but still cause this error:
<img width="962" alt="ScreenCapture" src="https://github.com/user-attachments/assets/02564f96-15ad-40ea-b471-18597d3fdd2f">

**Comment by X1a0He** [comment]
Please try clicking this button
<img width="630" alt="image" src="https://github.com/user-attachments/assets/88b32303-3502-4ea9-829b-cc57c65f91fd">

**Comment by ledunguit** [comment]
@X1a0He I realized that I need to open CC app before click `Reprocessing`, if not it can be installed. Thanks.

**Comment by 490398290** [comment]
@X1a0He Thank you so much for this tremendous update!

All working as expected! Please keep the project up because it's simply amazing!

Thank you Thank you Thank you!

**Comment by X1a0He** [comment]
> @X1a0He Thank you so much for this tremendous update!
> 
> All working as expected! Please keep the project up because it's simply amazing!
> 
> Thank you Thank you Thank you!

I'm so sorry to have kept you waiting so long, but it turned out great in the end, didn't it? Have a nice day
