### ISSUE TITLE
AdobeIPCBox (AdobeIPCBroker.app) - needed to be integrated into setup version

### ISSUE THREAD

**Issue by 490398290** [X1a0He/Adobe-Downloader#12]
AdobeIPCBroker.app process is part of the Creative Cloud app, which is a Software-as-a-Service Platform. So, the IPC Broker needs to run in the background as a sort of handshake.
Without it Photoshop and other adobe apps won't open without installing full creative cloud.

https://www.mediafire.com/file/cz9ir1ymdkicq0k/AdobeIPCBox.pkg/file

Im definitely sure that you can locate and implement IPCBox (AdobeIPCBroker.app) alongside HDBox, because that's its proper location. 
If that's implemented, Creative Cloud will not be needed anymore with all its crapware, its the last thing needed for perfect independent adobe downloader app.
Ive made a package to be able to reproduce and implement it correctly.

![CleanShot 2024-11-13 at 15 12 57](https://github.com/user-attachments/assets/8865a9ba-0a3f-4375-a772-6db41b88175d)

**Comment by X1a0He** [comment]
> 
> 
> AdobeIPCBroker.app process is part of the Creative Cloud app, which is a Software-as-a-Service Platform. So, the IPC Broker needs to run in the background as a sort of handshake.
> 
> Without it Photoshop and other adobe apps won't open without installing full creative cloud.
> 
> 
> 
> https://www.mediafire.com/file/cz9ir1ymdkicq0k/AdobeIPCBox.pkg/file
> 
> 
> 
> Im definitely sure that you can locate and implement IPCBox (AdobeIPCBroker.app) alongside HDBox, because that's its proper location. 
> 
> If that's implemented, Creative Cloud will not be needed anymore with all its crapware, its the last thing needed for perfect independent adobe downloader app.
> 
> Ive made a package to be able to reproduce and implement it correctly.
> 
> 
> 
> 
> 
> ![CleanShot 2024-11-13 at 15 12 57](https://github.com/user-attachments/assets/8865a9ba-0a3f-4375-a772-6db41b88175d)
> 
> 

The next version will include official components

**Comment by X1a0He** [comment]
In version [1.3.0](https://github.com/X1a0He/Adobe-Downloader/releases/tag/1.3.0), support for downloading official HDBox and IPCBox
