### ISSUE TITLE
无法处理setup组件

### ISSUE THREAD

**Issue by djhcod** [X1a0He/Adobe-Downloader#14]
设置界面显示setup组件正常，但是仍然无法安装应用程序。点击从GitHub下载组件时报错。
<img width="918" alt="截屏2024-11-14 12 12 04" src="https://github.com/user-attachments/assets/4523594a-f9ff-4824-a861-f8b328f52899">
<img width="712" alt="截屏2024-11-14 12 12 12" src="https://github.com/user-attachments/assets/b0819e26-6792-4687-9221-891a6b739b5e">
<img width="601" alt="截屏2024-11-14 12 12 50" src="https://github.com/user-attachments/assets/bf04f03a-3bd2-450a-a4d7-a6306ef6c352">

**Comment by X1a0He** [comment]
> 设置界面显示setup组件正常，但是仍然无法安装应用程序。点击从GitHub下载组件时报错。
> 
> <img width="918" alt="截屏2024-11-14 12 12 04" src="https://github.com/user-attachments/assets/4523594a-f9ff-4824-a861-f8b328f52899">
> 
> <img width="712" alt="截屏2024-11-14 12 12 12" src="https://github.com/user-attachments/assets/b0819e26-6792-4687-9221-891a6b739b5e">
> 
> <img width="601" alt="截屏2024-11-14 12 12 50" src="https://github.com/user-attachments/assets/bf04f03a-3bd2-450a-a4d7-a6306ef6c352">
> 
> 

预计今天更新新版本解决这些问题

**Comment by X1a0He** [comment]
请尝试最新版 [1.3.0](https://github.com/X1a0He/Adobe-Downloader/releases/tag/1.3.0)
