### ISSUE TITLE
InDesign isntallation error.

### ISSUE THREAD

**Issue by maccoder2024** [X1a0He/Adobe-Downloader#17]
I would like to start with thanking such a nice tool and also to whom you benefited from their work. 

I updated to version 1.3.0 and InDesign still gives 103 error while trying to install. Manual install attempt via Terminal also fails with error code 182. The install file has been downloaded after 1.3.0 update.

<img width="517" alt="Screenshot 2024-11-16 at 18 08 34" src="https://github.com/user-attachments/assets/1b3e160a-8570-4a07-9257-6b361ee88c8a">

**Comment by X1a0He** [comment]
> I would like to start with thanking such a nice tool and also to whom you benefited from their work.
> 
> I updated to version 1.3.0 and InDesign still gives 103 error while trying to install. Manual install attempt via Terminal also fails with error code 182. The install file has been downloaded after 1.3.0 update.
> 
> <img alt="Screenshot 2024-11-16 at 18 08 34" width="517" src="https://private-user-images.githubusercontent.com/188693304/386856017-1b3e160a-8570-4a07-9257-6b361ee88c8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NzAzNTMsIm5iZiI6MTczMTc3MDA1MywicGF0aCI6Ii8xODg2OTMzMDQvMzg2ODU2MDE3LTFiM2UxNjBhLTg1NzAtNGEwNy05MjU3LTZiMzYxZWU4OGM4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQxNTE0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDBmNDI4ODk1NmU5MWY0M2UyNzZlMzBkMzBiMGI3Y2RmZjQyZjNkZGVjNzJhZDhlMDZmYmVlY2VlNjQ0OWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1kurNxWK3G5OQ6a7ppUP85XAWbM6w6D1THGAehHlXJo">

Can you tell me if you are Apple Silicon or Intel, and also the version of InDesign?

**Comment by X1a0He** [comment]
I found a problem. The number of packages is a little less. Maybe it will be fixed in the next version.

**Comment by maccoder2024** [comment]
It's good that you figured it out. I use Silicon and tried latest version of InDesign 20.0.

That may help for testing.

**Comment by maccoder2024** [comment]
I also tried Premiere Pro 25.0 and received 103 error again. This time installing via Terminal worked with few warnings. I activated it with macked.app tool and opened without and issue. I am not sure whether these warnings indicate something to be fixed.


<img width="565" alt="Screenshot 2024-11-16 at 19 11 55" src="https://github.com/user-attachments/assets/57c9a586-a0d8-4e18-bc86-ee3b252f9e47">

**Comment by X1a0He** [comment]
> I also tried Premiere Pro 25.0 and received 103 error again. This time installing via Terminal worked with few warnings. I activated it with macked.app tool and opened without and issue. I am not sure whether these warnings indicate something to be fixed.
> 
> 
> 
> 
> 
> <img width="565" alt="Screenshot 2024-11-16 at 19 11 55" src="https://github.com/user-attachments/assets/57c9a586-a0d8-4e18-bc86-ee3b252f9e47">
> 
> 

I apologize again for any inconvenience caused. I will investigate the issue you mentioned

**Comment by X1a0He** [comment]
This problem has been fixed in version [v1.3.1](https://github.com/X1a0He/Adobe-Downloader/releases/tag/1.3.1)
