### ISSUE TITLE
Adobe Downloader failing to install Adobe After Effects 25.0 on M2 MacBook Air macOS 15.2. Getting exit code: 152 on command

### ISSUE THREAD

**Issue by MuggeGHQ** [X1a0He/Adobe-Downloader#19]
Hey

I have some info from @Theminer at MSJ √

Adobe Downloader failing to install Adobe After Effects 25.0 on M2 MacBook Air macOS 15.2. Getting exit code: 152 on command
CODE: [SELECT ALL](https://macserialjunkie.com/forum/viewtopic.php?p=1206821#)
sudo "/Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Setup" --install=1 --driverXML="/Users/*username*/Downloads/Adobe Downloader AEFT_25.0-en_US-macuniversal/driver.xml"
Found the fix for this, the 'application.json' in the AEFT folder has two 'non-core' modules for Cinema 4D. 
Remove references to these and it installs fine. For Apple Silicon users it should look something like this: https://pastebin.com/raw/RJMXe8h2

Hope you can fix that in your next release
Why not remove Cinema 4D all together ? nobody can use it anyway without a build in Patch or something else.

**Comment by X1a0He** [comment]
Hey GHQ, thank you for providing this helpful information. I analyzed the official download process and related package dependencies of ACC last night and found that some packages are indeed redundant and do not need to be downloaded. But for a more stable 1.4.0, I think I will spend more time studying it. Anyway, thank you very much

> 嘿
> 
> 我有一些信息@theminer在 MSJ √
> 
> Adobe Downloader 无法在 M2 MacBook Air macOS 15.2 上安装 Adob​​e After Effects 25.0。在命令 CODE: [SELECT](https://macserialjunkie.com/forum/viewtopic.php?p=1206821#)上获取退出代码：152 sudo "/Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Setup" --install=1 --driverXML="/Users/ _username_ /Downloads/Adobe Downloader AEFT_25.0-en_US-macuniversal/driver.xml" 找到此问题的修复方法，AEFT 文件夹中的“application.json”有两个用于 Cinema 4D 的“非核心”模块。 删除对这些的引用，它就可以正常安装。对于 Apple Silicon 用户，它应该看起来像这样： https: [//pastebin.com/raw/RJMXe8h2](https://pastebin.com/raw/RJMXe8h2)
> 
> 希望您能在下一个版本中修复这个问题 为什么不把 Cinema 4D 全部删除呢？不管怎样，没有内置补丁或其他东西，没人能使用它。

**Comment by X1a0He** [comment]
I spent an hour trying to simulate the download logic and package dependency organization of the official Adobe Creative Cloud, which looks very good, but I still want to make 1.4.0 better

<img width="1758" alt="X1a0He Adobe Downloader 2024-11-18 13 33 06" src="https://github.com/user-attachments/assets/3f7a9f93-67f8-4a65-8429-5a75e9ee8e74">

**Comment by Bentheminernz** [comment]
A solution I found for also including Cinema4D is in this file https://github.com/X1a0He/Adobe-Downloader/blob/main/Adobe%20Downloader/Utils/DownloadUtils.swift at line 754. It downloads only the core files, and ignores all non-core files yet still includes it in the .json. A solution could be to add a toggle to download non-core files if the user so wishes too and if they don't then make sure they aren't included in the .json

**Comment by X1a0He** [comment]
The download of 1.4.0 completely simulates the logic of ACC, so there is no need to worry about this.

> A solution I found for also including Cinema4D is in this file https://github.com/X1a0He/Adobe-Downloader/blob/main/Adobe%20Downloader/Utils/DownloadUtils.swift at line 754. It downloads only the core files, and ignores all non-core files yet still includes it in the .json. A solution could be to add a toggle to download non-core files if the user so wishes too and if they don't then make sure they aren't included in the .json
> 
> By making `isCore` always equal to true then it'll download Cinema4D and install it correctly

**Comment by MuggeGHQ** [comment]
Hey @X1a0He 

Sounds great √ if it works that would be perfect sure.
