### ISSUE TITLE
Lightroom Classic Exit Code: 107 on M2 Macos 15.0.1

### ISSUE THREAD

**Issue by PolarisYan** [X1a0He/Adobe-Downloader#20]
**need help**
<img width="890" alt="iShot_2024-11-19_02 07 32" src="https://github.com/user-attachments/assets/a0cb4f62-9b7e-4ab6-b145-8dd800a40e72">
**need help**
<img width="1001" alt="iShot_2024-11-19_02 08 30" src="https://github.com/user-attachments/assets/fa750c52-b8de-43da-b801-3e7bdac086c2">
**need help**

**Comment by X1a0He** [comment]
2024-11-19 09:53:00

![X1a0He Adobe Downloader 2024-11-19 09 52 33](https://github.com/user-attachments/assets/09c4b15f-28db-450c-9a58-c60f64531aca)

**Comment by PolarisYan** [comment]
> 2024-11-19 09:53:00 M1 Max macOS 15.1
> 
> ![X1a0He Adobe Downloader 2024-11-19 09 52 33](https://private-user-images.githubusercontent.com/43105322/387451016-09c4b15f-28db-450c-9a58-c60f64531aca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDcwODksIm5iZiI6MTczMjAwNjc4OSwicGF0aCI6Ii80MzEwNTMyMi8zODc0NTEwMTYtMDljNGIxNWYtMjhkYi00NTBjLTlhNTgtYzYwZjY0NTMxYWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4NTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YmUzMGQ3ZDRjYjVlZmE2NmEzNGI0OGM5MmUxYzRiMzZhNzA5ODQ5YThkNzBhYjU2ODhkY2ZhNmJjMmExMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7S6Rd_rcrDGizP-_jS63IPPvFHymIcDweF-JWoTXb3o)

So, should I upgrade macOS to 15.1 ? Or what deatils you need to debug the problem I encountered I can provide？

**Comment by X1a0He** [comment]
Error 107 means that the file is indeed or architecturally incorrect, but for Apple Silicon, I don't think it's an architectural issue, maybe it's a Setup component issue. You can try upgrading the Setup component version. Just click Download X1a0He CC component.

> > 2024-11-19 09:53:00 M1 Max macOS 15.1
> > ![X1a0He Adobe Downloader 2024-11-19 09 52 33](https://private-user-images.githubusercontent.com/43105322/387451016-09c4b15f-28db-450c-9a58-c60f64531aca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMDcwODksIm5iZiI6MTczMjAwNjc4OSwicGF0aCI6Ii80MzEwNTMyMi8zODc0NTEwMTYtMDljNGIxNWYtMjhkYi00NTBjLTlhNTgtYzYwZjY0NTMxYWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDA4NTk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5YmUzMGQ3ZDRjYjVlZmE2NmEzNGI0OGM5MmUxYzRiMzZhNzA5ODQ5YThkNzBhYjU2ODhkY2ZhNmJjMmExMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7S6Rd_rcrDGizP-_jS63IPPvFHymIcDweF-JWoTXb3o)
> 
> So, should I upgrade macOS to 15.1 ? Or what deatils you need to debug the problem I encountered I can provide？
