### ISSUE TITLE
点安装之后没反应

### ISSUE THREAD

**Issue by XXXinnnnnnn** [X1a0He/Adobe-Downloader#21]
<img width="851" alt="截屏2024-11-19 19 36 21" src="https://github.com/user-attachments/assets/a8f00c59-dab6-4e7d-b294-130212c07864">
这一步之后进度条不变化

**Comment by AppleJack-eng** [comment]
我也是这样  请问你解决了吗   我在终端输入安装，提示Progress: 0%Exit Code: 182

**Comment by X1a0He** [comment]
> 我也是这样 请问你解决了吗 我在终端输入安装，提示Progress: 0%Exit Code: 182

确保你的Setup组件为最新版，如果不是，请点击下载X1a0He CC

**Comment by AppleJack-eng** [comment]
你好  我点了下载还是这样  我已经试了很多次了  不知道是什么原因
