### ISSUE TITLE
安装了最新版的Lightroom，打开后弹出登陆页面，没有选择登陆直接关掉了登陆页面，软件就闪退了

### ISSUE THREAD

**Issue by shaobowangyou** [X1a0He/Adobe-Downloader#23]
你好博主，我安装了最新版的Lightroom，打开后弹出登陆页面，没有选择登陆直接关掉了登陆页面，软件就闪退了，请问这是怎么回事呢？

**Comment by X1a0He** [comment]
仅支持下载正版，不支持任何破解，如果你有购买订阅，登录账号即可使用

**Comment by shaobowangyou** [comment]
> 仅支持下载正版，不支持任何破解，有购买订阅，登录账号即可使用

了解了谢谢博主解答🫡
