### ISSUE TITLE
报错182

### ISSUE THREAD

**Issue by Obliviate1** [X1a0He/Adobe-Downloader#24]
下载安装illustrator29.1版本是报错182,客户端版本1.3.1,尝试多次都是182
<img width="962" alt="截屏2024-11-23 下午11 11 44" src="https://github.com/user-attachments/assets/ea854e11-b300-4d70-96ca-c287ec898e82">

**Comment by X1a0He** [comment]
确保你的Setup组件是最新版本

**Comment by AppleJack-eng** [comment]
你好 我这2个都点了 还是不行
![WechatIMG60](https://github.com/user-attachments/assets/1c2884fd-6b87-45fc-a1d7-e91337a1374e)

**Comment by AppleJack-eng** [comment]
> 下载安装illustrator29.1版本是报错182,客户端版本1.3.1,尝试多次都是182 <img alt="截屏2024-11-23 下午11 11 44" width="962" src="https://private-user-images.githubusercontent.com/93752735/389206215-ea854e11-b300-4d70-96ca-c287ec898e82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzU2MDgsIm5iZiI6MTczMjM3NTMwOCwicGF0aCI6Ii85Mzc1MjczNS8zODkyMDYyMTUtZWE4NTRlMTEtYjMwMC00ZDcwLTk2Y2EtYzI4N2VjODk4ZTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE1MjE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NGI5Y2ExNDI2Njc2YzUzOTBhY2M5NmI2MDQzNjdjZjA0ZjRmYzAyMDg5N2RiYWZlZGUyZDMwN2Q1Yjk4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xaUN2LOuFkcnTIUKzBaNZUZ8PI9meB2lTFIXoQjJz8Y">



> 下载安装illustrator29.1版本是报错182,客户端版本1.3.1,尝试多次都是182 <img alt="截屏2024-11-23 下午11 11 44" width="962" src="https://private-user-images.githubusercontent.com/93752735/389206215-ea854e11-b300-4d70-96ca-c287ec898e82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzU2MDgsIm5iZiI6MTczMjM3NTMwOCwicGF0aCI6Ii85Mzc1MjczNS8zODkyMDYyMTUtZWE4NTRlMTEtYjMwMC00ZDcwLTk2Y2EtYzI4N2VjODk4ZTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE1MjE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NGI5Y2ExNDI2Njc2YzUzOTBhY2M5NmI2MDQzNjdjZjA0ZjRmYzAyMDg5N2RiYWZlZGUyZDMwN2Q1Yjk4ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xaUN2LOuFkcnTIUKzBaNZUZ8PI9meB2lTFIXoQjJz8Y">

我和你一样  我已经试了很多次了

**Comment by Obliviate1** [comment]
会不会Adobe的下载服务器有问题,仔细观察了一下下载过程,会失败报错显示网络中断

**Comment by X1a0He** [comment]
> > > 并不是，182好像是依赖包缺失了，先用着 Drovesk01 的吧 [adobe-packager](https://github.com/Drovosek01/adobe-packager)
> > 
> > 
> > 好的,谢谢大佬
> 
> 你好 请问什么意思啊 有点不懂

最近没时间修复，但182就是意味着下载的依赖包缺失，用着前辈Drovesk01的库吧，我的库是受了他的启发才开发的

**Comment by AppleJack-eng** [comment]
> > > > 并不是，182好像是依赖包缺失了，先用着 Drovesk01 的吧 [adobe-packager](https://github.com/Drovosek01/adobe-packager)
> > > 
> > > 
> > > 好的,谢谢大佬
> > 
> > 
> > 你好 请问什么意思啊 有点不懂
> 
> 最近没时间修复，但182就是意味着下载的依赖包缺失，用着前辈Drovesk01的库吧，我的库是受了他的启发才开发的

好的 谢谢大佬

**Comment by X1a0He** [comment]
M1 Max macOS 15.1 亲测没问题
<img width="880" alt="image" src="https://github.com/user-attachments/assets/356f0c0b-2432-4987-8b33-7e609444f9de">

<img width="630" alt="image" src="https://github.com/user-attachments/assets/52883b38-e308-4524-9602-78d46687e25c">

**Comment by Obliviate1** [comment]
> M1 Max macOS 15.1 亲测没问题
> 
> <img width="880" alt="image" src="https://github.com/user-attachments/assets/356f0c0b-2432-4987-8b33-7e609444f9de">
> 
> 
> 
> <img width="630" alt="image" src="https://github.com/user-attachments/assets/52883b38-e308-4524-9602-78d46687e25c">
> 
> 

me可以安装只有ai不行，我再试试

**Comment by AppleJack-eng** [comment]
> 并不是，182好像是依赖包缺失了，先用着 Drovesk01 的吧 [adobe-packager](https://github.com/Drovosek01/adobe-packager)

你好 大佬  我pr能下载   当我下载ps时候回报182错误代码。我m1pro芯片

**Comment by X1a0He** [comment]
> > 并不是，182好像是依赖包缺失了，先用着 Drovesk01 的吧 [adobe-packager](https://github.com/Drovosek01/adobe-packager)
> 
> 你好 大佬 我pr能下载 当我下载ps时候回报182错误代码。我m1pro芯片

如果你用Drovesk01的包也是182，那就是你的问题了

**Comment by Obliviate1** [comment]
> > 并不是，182好像是依赖包缺失了，先用着 Drovesk01 的吧 [adobe-packager](https://github.com/Drovosek01/adobe-packager)
> 
> 
> 
> 你好 大佬  我pr能下载   当我下载ps时候回报182错误代码。我m1pro芯片
> 
> 

重装一边系统完美解决了🤣🤣

**Comment by AppleJack-eng** [comment]
> > > 并不是，182好像是依赖包缺失了，先用着 Drovesk01 的吧 [adobe-packager](https://github.com/Drovosek01/adobe-packager)
> > 
> > 
> > 你好 大佬 我pr能下载 当我下载ps时候回报182错误代码。我m1pro芯片
> 
> 如果你用Drovesk01的包也是182，那就是你的问题了

我没有用Drovesk01的包，感觉有点复杂。我还是用的您的项目

**Comment by AppleJack-eng** [comment]
> > > 并不是，182好像是依赖包缺失了，先用着 Drovesk01 的吧 [adobe-packager](https://github.com/Drovosek01/adobe-packager)
> > 
> > 
> > 你好 大佬 我pr能下载 当我下载ps时候回报182错误代码。我m1pro芯片
> 
> 如果你用Drovesk01的包也是182，那就是你的问题了

大佬您好  我已经测试了，ps我下载最新版26、26.1会出现182的错误，但我下载2024的版本不会报错.目前就出现这些错误，我下载其他的都能顺利下载。感谢大佬的项目

**Comment by AppleJack-eng** [comment]
> > > 并不是，182好像是依赖包缺失了，先用着 Drovesk01 的吧 [adobe-packager](https://github.com/Drovosek01/adobe-packager)
> > 
> > 
> > 你好 大佬 我pr能下载 当我下载ps时候回报182错误代码。我m1pro芯片
> 
> 如果你用Drovesk01的包也是182，那就是你的问题了

大佬您好  我已经测试了，ps我下载最新版26、26.1会出现182的错误，但我下载2024的版本不会报错.目前就出现这些错误，我下载其他的都能顺利下载。感谢大佬的项目

**Comment by X1a0He** [comment]
看了下来，感觉还是下载包有问题，最近没时间修复，如果老版本能用就用老版本，老版本用不了的话，就用Drovesk的包
