### ISSUE TITLE
Typo in English interface

### ISSUE THREAD

**Issue by maccoder2024** [X1a0He/Adobe-Downloader#26]
I just noticed a minor typo in English text.

It says Downloadind not Downloading right before the install file name. Not a big deal at all but such a nice work would be nicer with correct spelling :)

<img width="628" alt="Screenshot 2024-11-23 at 19 27 36" src="https://github.com/user-attachments/assets/290a8cca-fd07-4ca7-b335-4efed885ce7f">

**Comment by X1a0He** [comment]
Thank you very much, you’re very observant.
