### ISSUE TITLE
报错-1

### ISSUE THREAD

**Issue by yuebaiqaq** [X1a0He/Adobe-Downloader#27]
安装失败：安装失败：Setup 组件未被处理（退出代码：-1）
macOS Sequoia
版本15.1.1

**Comment by RealKen** [comment]
i have the same issue when trying to install photoshop. im on macOS Sonoma 14.5 though.

**Comment by X1a0He** [comment]
不处理Setup组件永远都安装不了，说了很多遍了，不想再说了，自己看readme.md

1. 请确保Setup组件版本为最新
2. 请确保Setup组件已被处理

解决方法
- 右上角设置 - 下载 X1a0He CC (可同时更新Setup组件版本和处理Setup组件)
- 右上角设置 - 重新处理 (可重新处理Setup组件)

**Comment by wjskaisa** [comment]
一样，处理完了还是安装不了，你解决了吗

**Comment by 44-LewisHamilton** [comment]
更新新版下载器
