### ISSUE TITLE
indesign 20.0.1报错146

### ISSUE THREAD

**Issue by CISHENZF** [X1a0He/Adobe-Downloader#29]
![iShot_2024-11-26_16 47 29](https://github.com/user-attachments/assets/995d632f-cc02-4c98-a55c-45177f12b23b)
<img width="600" alt="iShot_2024-11-26_16 48 30" src="https://github.com/user-attachments/assets/a02346bd-1d84-4619-a1ff-9bb9b75daacd">
<img width="433" alt="iShot_2024-11-26_16 56 26" src="https://github.com/user-attachments/assets/f7c147fe-b984-41df-b2fe-9691dad5840d">

多次重新下载，并使用旧版本1.2.0都报错“146”，代码安装也一样

**Comment by X1a0He** [comment]
系统设置 - 隐私与安全 - App管理 - 勾选Adobe Downloader

**Comment by CISHENZF** [comment]
<img width="552" alt="iShot_2024-11-26_17 06 41" src="https://github.com/user-attachments/assets/c6c03263-5445-44f2-bb05-48c8a07020d2">
 仍然不行

**Comment by CISHENZF** [comment]
intel 15.1.1
刚才下载Adobe Downloader 1.1.0，成功安装了
