### ISSUE TITLE
HELP install an application on an unsupported version of macOS

### ISSUE THREAD

**Issue by vichy00** [X1a0He/Adobe-Downloader#30]
I'm trying to run the downloader on mac os 10.15 Catalina, but I wasn't able to work my way around it. I follow the instructs but:

1) When I downloaded  the ACCCx6_4_0_361 from ADOBE for my version - it requested for me to log - didn't give me the off-line option. // 2) I cannot install Adobe Downloader - since requires 12+ and I didn't find the json file

Probably I'm doing something wrong, I'm newbie. May you kindly help me? thx.

**Comment by X1a0He** [comment]
Only for macOS 12.0+
