### ISSUE TITLE
PS安装失败, Exit code: 133

### ISSUE THREAD

**Issue by LGinC** [X1a0He/Adobe-Downloader#40]
<img width="789" alt="image" src="https://github.com/user-attachments/assets/59ae6061-7358-4e3a-a17b-10c9797e61ec" />

<img width="1006" alt="image" src="https://github.com/user-attachments/assets/f16f2085-7a21-4390-b522-835096b986ec" />

<img width="598" alt="image" src="https://github.com/user-attachments/assets/d210da0f-d1df-429c-91f6-d1ab6293f9c1" />

Version: 1.3.1
PhotoShop 25.6
intel

**Comment by X1a0He** [comment]
也许是磁盘空间不足

**Comment by LGinC** [comment]
还真是，把垃圾篓清空了就可以了
