### ISSUE TITLE
总是连接不上helper

### ISSUE THREAD

**Issue by AMlhdSan** [X1a0He/Adobe-Downloader#42]
总是连接不上helper，重新安装也没用，M2 pro的芯片，谢谢

**Comment by cui0v0** [comment]
M4 Mac mini也遇到了

**Comment by AMlhdSan** [comment]
求助啊啊啊！我用packeger还是好的啊

**Comment by X1a0He** [comment]
你用packager是好的有没有可能是因为我修改了安装组件，helper连不上可能是系统的问题，用命令行安装

**Comment by AMlhdSan** [comment]
> 你用packager是好的有没有可能是因为我修改了安装组件，helper连不上可能是系统的问题，用命令行安装

？用命令行安装哪个？您的软件还是packager？

**Comment by X1a0He** [comment]
用packager吧

**Comment by AMlhdSan** [comment]
好的，谢谢作者在百忙中抽空解决！
