### ISSUE TITLE
In order to be able to download and install successfully, you need to modify the Adobe Setup program ?

### ISSUE THREAD

**Issue by MuggeGHQ** [X1a0He/Adobe-Downloader#5]
Hey

Big thanks for this great software. I have a question. Nr 2
In order to be able to download and install successfully, you need to modify the Adobe Setup program, very grateful for the solution provided by [QiuChenly]
What exactly is it we need to do after downloading the Adobe app ? I saw when the download is finish you have a folder with the Adobe Programs folders. But what kind of modification are you talking about. Thx a lot √

**Comment by X1a0He** [comment]
> Hey
> 
> 
> 
> Big thanks for this great software. I have a question. Nr 2
> 
> In order to be able to download and install successfully, you need to modify the Adobe Setup program, very grateful for the solution provided by [QiuChenly]
> 
> What exactly is it we need to do after downloading the Adobe app ? I saw when the download is finish you have a folder with the Adobe Programs folders. But what kind of modification are you talking about. Thx a lot √

I'm happy to answer your question. You don't need to do anything to download and install, because Adobe Downloader has already done everything for you, so you don't have to worry about any security issues, enjoy it. :)

**Comment by MuggeGHQ** [comment]
> > Hey
> > Big thanks for this great software. I have a question. Nr 2
> > In order to be able to download and install successfully, you need to modify the Adobe Setup program, very grateful for the solution provided by [QiuChenly]
> > What exactly is it we need to do after downloading the Adobe app ? I saw when the download is finish you have a folder with the Adobe Programs folders. But what kind of modification are you talking about. Thx a lot √
> 
> I'm happy to answer your question. You don't need to do anything to download and install, because Adobe Downloader has already done everything for you, so you don't have to worry about any security issues, enjoy it. :)

Ah i see. Ok i misunderstand the info then. Thats really cool, thx a lot for this great peace of software √

**Comment by X1a0He** [comment]
> > > Hey
> 
> > > Big thanks for this great software. I have a question. Nr 2
> 
> > > In order to be able to download and install successfully, you need to modify the Adobe Setup program, very grateful for the solution provided by [QiuChenly]
> 
> > > What exactly is it we need to do after downloading the Adobe app ? I saw when the download is finish you have a folder with the Adobe Programs folders. But what kind of modification are you talking about. Thx a lot √
> 
> > 
> 
> > I'm happy to answer your question. You don't need to do anything to download and install, because Adobe Downloader has already done everything for you, so you don't have to worry about any security issues, enjoy it. :)
> 
> 
> 
> Ah i see. Ok i misunderstand the info then. Thats really cool, thx a lot for this great peace of software √

Thank you again for liking it. Wishing you a wonderful day.
