### ISSUE TITLE
Intel Vs ARM

### ISSUE THREAD

**Issue by MuggeGHQ** [X1a0He/Adobe-Downloader#6]
Hey again. Sorry i forgot to ask you another question.
I can see you deleted the other conversation but just want to ask.
The Downloader app. I can see in the preferences  it say, "Download Apple Silicon" √
But how do you download an Intel version for example ? or a Universal version.

Thanks again

**Comment by X1a0He** [comment]
> Hey again. Sorry i forgot to ask you another question.
> 
> I can see you deleted the other conversation but just want to ask.
> 
> The Downloader app. I can see in the preferences  it say, "Download Apple Silicon" √
> 
> But how do you download an Intel version for example ? or a Universal version.
> 
> 
> 
> Thanks again

Nice to communicate with you again. The current program will automatically detect the chip architecture. If you are an Apple Silicon, the corresponding option will be automatically checked. If you are an Intel chip, the corresponding option will not be checked. Regardless, the download will be based on the most suitable chip architecture, but there are also users who need to download apps of other architectures
For example, if you are an M-chip and want to download Intel architecture apps, simply uncheck the option, and all M-chip products will be automatically filtered out. Of course, you can see the corresponding version on each version number selection page and under the version number, such as universal, osx10, arm64, etc. I hope this can answer your question. :)

**Comment by MuggeGHQ** [comment]
> > Hey again. Sorry i forgot to ask you another question.
> > I can see you deleted the other conversation but just want to ask.
> > The Downloader app. I can see in the preferences  it say, "Download Apple Silicon" √
> > But how do you download an Intel version for example ? or a Universal version.
> > Thanks again
> 
> Nice to communicate with you again. The current program will automatically detect the chip architecture. If you are an Apple Silicon, the corresponding option will be automatically checked. If you are an Intel chip, the corresponding option will not be checked. Regardless, the download will be based on the most suitable chip architecture, but there are also users who need to download apps of other architectures For example, if you are an M-chip and want to download Intel architecture apps, simply uncheck the option, and all M-chip products will be automatically filtered out. Of course, you can see the corresponding version on each version number selection page and under the version number, such as universal, osx10, arm64, etc. I hope this can answer your question. :)

Yeah thats what i ment. I did noticed it automatically detected my chip but if my chip was M3 for example and need it for Intel. How do i do that. But you say, uncheck the automatically detection and it will use Universal or just Intel ? How to choose.

**Comment by X1a0He** [comment]
> > > Hey again. Sorry i forgot to ask you another question.
> 
> > > I can see you deleted the other conversation but just want to ask.
> 
> > > The Downloader app. I can see in the preferences  it say, "Download Apple Silicon" √
> 
> > > But how do you download an Intel version for example ? or a Universal version.
> 
> > > Thanks again
> 
> > 
> 
> > Nice to communicate with you again. The current program will automatically detect the chip architecture. If you are an Apple Silicon, the corresponding option will be automatically checked. If you are an Intel chip, the corresponding option will not be checked. Regardless, the download will be based on the most suitable chip architecture, but there are also users who need to download apps of other architectures For example, if you are an M-chip and want to download Intel architecture apps, simply uncheck the option, and all M-chip products will be automatically filtered out. Of course, you can see the corresponding version on each version number selection page and under the version number, such as universal, osx10, arm64, etc. I hope this can answer your question. :)
> 
> 
> 
> Yeah thats what i ment. I did noticed it automatically detected my chip but if my chip was M3 for example and need it for Intel. How do i do that. But you say, uncheck the automatically detection and it will use Universal or just Intel ? How to choose.

Most products are Universal, while some products have corresponding architectures. The specific target architecture of the product will be marked below the version number, and you can easily find it

**Comment by MuggeGHQ** [comment]
> > > > Hey again. Sorry i forgot to ask you another question.
> > 
> > 
> > > > I can see you deleted the other conversation but just want to ask.
> > 
> > 
> > > > The Downloader app. I can see in the preferences  it say, "Download Apple Silicon" √
> > 
> > 
> > > > But how do you download an Intel version for example ? or a Universal version.
> > 
> > 
> > > > Thanks again
> > 
> > 
> > > 
> > 
> > 
> > > Nice to communicate with you again. The current program will automatically detect the chip architecture. If you are an Apple Silicon, the corresponding option will be automatically checked. If you are an Intel chip, the corresponding option will not be checked. Regardless, the download will be based on the most suitable chip architecture, but there are also users who need to download apps of other architectures For example, if you are an M-chip and want to download Intel architecture apps, simply uncheck the option, and all M-chip products will be automatically filtered out. Of course, you can see the corresponding version on each version number selection page and under the version number, such as universal, osx10, arm64, etc. I hope this can answer your question. :)
> > 
> > 
> > Yeah thats what i ment. I did noticed it automatically detected my chip but if my chip was M3 for example and need it for Intel. How do i do that. But you say, uncheck the automatically detection and it will use Universal or just Intel ? How to choose.
> 
> Most products are Universal, while some products have corresponding architectures. The specific target architecture of the product will be marked below the version number, and you can easily find it

Alright then. Thx again for everything √
