### ISSUE TITLE
安装失败：安装程序调用失败，请联系X1a0He

### ISSUE THREAD

**Issue by wyek1n** [X1a0He/Adobe-Downloader#7]
Lightroom安装失败
Exit Code:-1
错误详情：
安装失败：安装程序调用失败，请联系X1a0He

机型：M1 Pro
系统：15.2 Beta版(24C5073e)

**Comment by X1a0He** [comment]
请对 Setup 程序进行备份，在备份的过程中，会对Setup程序进行相关处理
