### ISSUE TITLE
Photoshop and Bridge won't install

### ISSUE THREAD

**Issue by telepati** [X1a0He/Adobe-Downloader#8]
Photoshop and Bridge give an error "Exit Code: 146"  when I try to install. Illustrator, InDesign, and Acrobat Installed without any problem. But these two always giving same error. ACCD already installed. I delete the files and re-downloaded but still getting same error. It looks like I must give a permission, but your downloader is not direct to correct permission settings. Which permission should I need?

**Comment by X1a0He** [comment]
You can add permissions by following the steps below
System Settings - Privacy and Security - App Management - Add Adobe Downloader

> Photoshop and Bridge give an error "Exit Code: 146" when I try to install. Illustrator, InDesign, and Acrobat Installed without any problem. But these two always giving same error. ACCD already installed. I delete the files and re-downloaded but still getting same error. It looks like I must give a permission, but your downloader is not direct to correct permission settings. Which permission should I need?

**Comment by telepati** [comment]
Now it's start to give Exit Code: -1 error.

**Comment by 490398290** [comment]
You need to add also IPCBox in /Library/Application Support/Adobe Desktop Common.

HDBox is minimal runtime which allows installation of the apps 
IPCBox is runtime needed for photoshop communication for various functions between the app. It's also known as IPC Broker.app and needs to be U2B.
Thank you for this great tool!

IPCBroker it is mandatory, at least for Photoshop to run without Creative Cloud. 
Creative Cloud installs IPCBroker.app automatically inside IPCBox folder.

**Comment by telepati** [comment]
@490398290 I have already that app. I've already downloaded and installed InDesign, Illustrator, and Acrobat with Adobe Downloader Tool. But I can download Photoshop and Bridge but can't install it.

**Comment by X1a0He** [comment]
> @490398290 I have that app. I've already downloaded and installed InDesign, Illustrator, and Acrobat with Adobe Downloader Tool. But I can download Photoshop and Bridge but can't install it. 

Please reprocess the Setup component

**Comment by telepati** [comment]
@X1a0He This time it was almost over but got this error Progress: 98%Exit Code: 0    By the way, I fully uninstall the Adobe Downloader Tool with leftovers. Re-installed it, but it wouldn't help either.

**Comment by X1a0He** [comment]
> @X1a0He This time it was almost over but got this error Progress: 98%Exit Code: 0

Exit Code: 0 is not an error, it is the code for a successful installation

**Comment by telepati** [comment]
@X1a0He You're absolutely right. I realized it a little late. :) Thank you. I close the issue.

**Comment by 490398290** [comment]
@X1a0He I reprocessed the app but still IPCBox didn't appear. I had to manually install it otherwise photoshop won't start.
Mac mini M1 Sequoia.
